# defines the activity to perform for this service (only works for the list of constants below)
int8 				control_code

# location and file_name to save as (uses a default location if save is the function chosen and this is left empty)
string 				file_name

# for the stop command if this is set to true it will interrupt the current behavior mid execution, otherwise it will wait until the current behavior finishes
bool 				interrupt

# fairly self explanatory
int8 				STOP=0
int8 				START=1
int8 				SAVE_TO_FILE=2
int8				RESET=3
---
# returns whether or not the requested service succeeded
bool 				success

string				error_msg