# resource types for the cooking environment
### STATIC OBJECTS ###
int8                    COUNTER=4
int8                    CUT_BOARD=5
int8                    TOASTER=6
int8                    POT=7
int8                    BLENDER=8
int8                    PAN=9
int8                    PLATE_DISPENSER=10
int8                    BREAD_DISPENSER=11
int8                    PASTA_DISPENSER=12
int8                    ICE_DISPENSER=13
int8                    ONION_DISPENSER=14
int8                    EGG_DISPENSER=15
int8                    BANANA_DISPENSER=16
int8                    STRAWBERRY_DISPENSER=17
int8                    TOMATO_DISPENSER=18
int8                    LETTUCE_DISPENSER=19
int8                    ABSORBING_DELIVER_SQUARE=20

### DYNAMIC OBJECTS ###
int8                    PLATE=21
int8                    BREAD=22
int8                    PASTA=23
int8                    ICE=24
int8                    ONION=25
int8                    EGG=26
int8                    BANANA=27
int8                    STRAWBERRY=28
int8                    TOMATO=29
int8                    LETTUCE=30
int8                    BREAD_CHOPPED=31
int8                    BREAD_TOASTED=32
int8                    PASTA_COOKED=33
int8                    ONION_CHOPPED=34
int8                    EGG_FRIED=35
int8                    BANANA_CHOPPED=36
int8                    TOMATO_CHOPPED=37
int8                    TOMATO_FRIED=38
int8                    LETTUCE_CHOPPED=39
int8                    SMOOTHIE=40