### FOR USE BY MAIN SERVER ONLY
# type of request (see constants below)
int8 				type
	
# optional: node name to add or remove (added nodes are already constructed by the server)
string 				node_name

# optional: type of node to become
string 				plugin_name

# optional: params to change in the node this request was sent to
string[] 			params

# msg constants (self explanatory)
int8 				ADD=0
int8 				REMOVE=1
int8 				PARAM_UPDATE=2
int8 				MUTATE=3
---
# whether the request was successfully processed, and any error messages
bool 				success
string 				error_msg