
name: Doxygen Actions

run-name: ${{ github.actor }}
on: push
jobs:
  doxygen-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - run: git checkout main
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: ./config
      - run: |
          git fetch origin 
          git checkout gh-pages
          git add -f ./html ./latex
          git config --global user.name "Tyler Becker"
          git config --global user.email "tylerjohnbecker@user.noreply.github.com"
          git commit -m "doxygen changes"
          git push origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cd .. && rm -rf ${{ github.workspace }}