
name: Doxygen Actions

run-name: ${{ github.actor }}
on: push
jobs:
  doxygen-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - run: git checkout main
      - run: doxygen ./config
      - run: git checkout gh-pages
      - run: git add ./html ./latex
      - run: git commit -m "doxygen changes"
      - run: git push origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cd .. && rm -rf ${{ github.workspace }}