
name: Build and Test dhtt

run-name: ${{ github.actor }}
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    permissions:
      contents: write
      issues: read
    steps:
      # taken from example here: https://github.com/marketplace/actions/setup-ros-environment
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with: 
          required-ros-distributions: jazzy
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
            # REQUIRED: Specify the required boost version
            # A list of supported versions can be found here:
            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
            boost_version: 1.78.0
            # OPTIONAL: Specify a platform version
            platform_version: 22.04
            # OPTIONAL: Specify a custom install location
            boost_install_dir: /home/runner/some_directory
            # OPTIONAL: Specify a toolset
            toolset: gcc
            # OPTIONAL: Specify an architecture
            arch: x86

      # NOTE: If a boost version matching all requirements cannot be found,
      # this build step will fail
      - name: Setup Workspace
        run: |
          source /opt/ros/jazzy/setup.bash && ros2 run --help
          mkdir temp_ws && cd temp_ws
          mkdir src && cd src 
          git clone https://github.com/tylerjohnbecker/dhtt_base.git
          cd ..
          colcon build
          source install/setup.bash
        shell: bash
      - name: Start Server
        run: ros2 run dhtt start_server &
      - name: Run Tests
        run: |
          colcon test --packages-select dhtt --event-handlers console_cohesion+ --return-code-on-test-failure
